# Generated by Django 3.1.1 on 2020-10-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=10)),
                ('parent_phone_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('confirm_password', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=10)),
                ('subject1', models.CharField(max_length=10)),
                ('subject2', models.CharField(max_length=10)),
                ('subject3', models.CharField(max_length=10)),
                ('subject4', models.CharField(max_length=10)),
                ('subject5', models.CharField(max_length=10)),
            ],
        ),
    ]
