# Generated by Django 3.1.1 on 2020-10-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(default='', max_length=10),
        ),
    ]
