# Generated by Django 3.1.3 on 2020-11-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subject1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject4',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject5',
            field=models.CharField(max_length=50),
        ),
    ]
