# Generated by Django 3.1.3 on 2020-11-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_os_uploadassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='os_uploadassignment',
            name='assignment',
            field=models.CharField(default='', max_length=30),
        ),
    ]
