# Generated by Django 3.1.3 on 2020-11-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20201123_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='os_uploadassignment',
            name='assignment',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='os_uploadassignment',
            name='file',
            field=models.FileField(default='', upload_to='student/uploadAssignment'),
        ),
    ]
