# Generated by Django 3.1.3 on 2020-11-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20201123_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='CN_UploadAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.CharField(max_length=30)),
                ('file', models.FileField(default='', upload_to='student/uploadAssignment')),
                ('Student_name', models.CharField(max_length=30)),
            ],
        ),
    ]
