# Generated by Django 3.1.3 on 2020-11-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_cn_uploadassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Java_UploadAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.CharField(max_length=30)),
                ('file', models.FileField(default='', upload_to='student/uploadAssignment')),
                ('Student_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OOAD_UploadAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.CharField(max_length=30)),
                ('file', models.FileField(default='', upload_to='student/uploadAssignment')),
                ('Student_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project_UploadAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.CharField(max_length=30)),
                ('file', models.FileField(default='', upload_to='student/uploadAssignment')),
                ('Student_name', models.CharField(max_length=30)),
            ],
        ),
    ]
