# Generated by Django 3.1.3 on 2020-11-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(max_length=30),
        ),
    ]
