# Generated by Django 3.1.3 on 2020-11-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20201106_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cn_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Java_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ooad_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='')),
                ('date', models.DateField()),
            ],
        ),
    ]
