# Generated by Django 3.1.3 on 2020-11-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_cn_assignment_java_assignment_ooad_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default='', upload_to='teacher/images'),
        ),
    ]
