# Generated by Django 3.1.3 on 2020-11-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='os_assignment',
            name='file',
            field=models.FileField(upload_to='teacher/Assignment_file'),
        ),
    ]
