# Generated by Django 3.1.3 on 2020-11-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20201119_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='os_assignment',
            name='file',
            field=models.FileField(default='', upload_to='teacher/Assignment_file'),
        ),
    ]
