# Generated by Django 3.1.3 on 2020-11-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_auto_20201119_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='os_assignment',
            name='file',
            field=models.ImageField(default='', upload_to='media/teacher/Assignment_file'),
        ),
    ]
