# Generated by Django 3.1.3 on 2020-11-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOD', '0002_auto_20201028_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='photo',
            field=models.ImageField(default='', upload_to='hod/images'),
        ),
    ]
