# Generated by Django 3.1.3 on 2020-11-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOD', '0003_hod_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('confirm_passward', models.CharField(max_length=20)),
                ('photo', models.ImageField(default='', upload_to='hod/images')),
            ],
        ),
        migrations.DeleteModel(
            name='HOD',
        ),
    ]
